### ISSUE TITLE
RPC Images

### ISSUE THREAD

**Issue by ColexDev** [BubbatheVTOG/coc-discord#11]
When editing a file the large image does not show up with the language you are using. I have only tested this for C and C++ but there are no large images showing up for either of them.

**Comment by BubbatheVTOG** [comment]
That's lame. I'll take a look at this after work.

**Comment by ColexDev** [comment]
![image](https://user-images.githubusercontent.com/72173656/120588042-76fae700-c404-11eb-95a2-cc6408812e98.png)
I forgot to include an image, here it is.

**Comment by BubbatheVTOG** [comment]
ahhhh well there is you're problem... you have a black discord theme. The icons that I chose for `c` and `c++` are also black. Before I investigate further can you confirm that this is the case and not that there is no image?

(If I remember right, I chose these instances of the language icons because they were the only ones that I could find that had transparent backgrounds. Many of the typical blue `c` and `c++` icons had white backgrounds. Non-transparent backgrounds for these icons do not look very good.)

![image](https://user-images.githubusercontent.com/8262112/120738415-d23ce000-c4bd-11eb-8e4a-a24de3a1f0cd.png)

**Comment by ColexDev** [comment]
That was the issue! I never even thought about that as I have never seen a black c/c++ logo, sorry for wasting your time. Thank you so much for the assistance!
